#!/bin/bash
# Decide whether a pull request can affect the container image (Issue #1929).
#
# Usage:
#   detect-image-changes.sh <base-commit> <head-commit>
#
# Prints `image=true` when a path that can change the built image differs
# between the two commits, `image=false` when none does, and appends the same
# `image=<value>` line to $GITHUB_OUTPUT when that variable is set.
#
# Exit codes:
#   0  the filter ran and reached a decision
#   2  the filter could NOT run — bad usage, not a git repository, a commit
#      missing from the local object store, or a failed `git diff`
#
# Why exit 2 exists (Issue #1929): this filter used to be an inline `run:`
# block in `.github/workflows/container-build.yml` whose
# `git diff --name-only "${base}" "${head}" … || true` swallowed every
# failure. A diff that could not run yielded an empty changed-file list, which
# reads as "nothing image-affecting changed", so the 11-minute build was
# skipped and the REQUIRED `container` check reported green having verified
# nothing — the same silent-failure class as Issue #1891. A filter that cannot
# run now stops the job instead of waving the pull request through.
#
# Australian English is used throughout (behaviour, colour, organisation).
set -euo pipefail

readonly PROGRAM_NAME="${0##*/}"

# The only paths that can change what the image build produces.
#
# `container/**` is the image definition itself (Containerfile, entrypoint,
# tools manifest, provider scripts) and this workflow drives the build.
#
# Issue #1584 adds the two generator paths: the Playwright MCP config the
# workflow probes is generated by worker/deno/setup/screenshot.ts, so a pull
# request changing the generator (or its unit test) changes what the probe
# exercises while touching nothing under container/**.
readonly IMAGE_PATHS=(
  'container/**'
  '.github/workflows/container-build.yml'
  'worker/deno/setup/screenshot.ts'
  'worker/deno/tests/setup_screenshot_test.ts'
)

usage() {
  echo "usage: ${PROGRAM_NAME} <base-commit> <head-commit>" >&2
}

if [[ $# -ne 2 ]]; then
  echo "ERROR: expected exactly two commit arguments, got $#." >&2
  usage
  exit 2
fi

base="$1"
head="$2"

for label in base head; do
  value="${!label}"
  if [[ -z "$value" ]]; then
    echo "ERROR: empty ${label} commit argument." >&2
    usage
    exit 2
  fi
done

# Paths from `git diff` are repository-root relative, so decide from the root
# whatever directory the caller invoked us in.
if ! toplevel="$(git rev-parse --show-toplevel 2>/dev/null)"; then
  echo "ERROR: not inside a git repository — cannot diff ${base}..${head}." >&2
  exit 2
fi
cd "$toplevel"

for label in base head; do
  value="${!label}"
  if ! git rev-parse --verify --quiet "${value}^{commit}" >/dev/null; then
    echo "ERROR: ${label} commit ${value} is not in the local object store." >&2
    echo "  The checkout is too shallow to diff against it. Fetch it first" >&2
    echo "  (actions/checkout with fetch-depth: 0, or an explicit" >&2
    echo "  'git fetch origin ${value}')." >&2
    exit 2
  fi
done

changed_list="$(mktemp)"
trap 'rm -f "$changed_list"' EXIT
# No `|| true` here, deliberately: a diff that cannot run must stop the job
# rather than hand it an empty change set that reads as "nothing to build".
if ! git diff --name-only "$base" "$head" -- "${IMAGE_PATHS[@]}" \
  >"$changed_list"; then
  echo "ERROR: 'git diff ${base} ${head}' failed — see the error above." >&2
  exit 2
fi

changed=()
while IFS= read -r path; do
  [[ -n "$path" ]] || continue
  changed+=("$path")
done <"$changed_list"

emit() {
  echo "$1"
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    echo "$1" >>"$GITHUB_OUTPUT"
  fi
}

if [[ ${#changed[@]} -gt 0 ]]; then
  emit "image=true"
  echo "image-affecting changes:"
  for path in "${changed[@]+"${changed[@]}"}"; do
    echo "  ${path}"
  done
else
  emit "image=false"
  echo "no image-affecting changes — the image checks are skipped and reported as passed"
fi
