#!/usr/bin/env bash
# Gemini CLI provider installation fragment (Issue #4107, parent #4102).
#
# The third provider the image can install, and in Quorum mode the judge
# rather than a planner. As with claude.sh and codex.sh, adding it is this
# file plus a container/tools.json `providers` entry and a descriptor in
# worker/deno/lib/agent_provider.ts — the base Containerfile and
# container/install-providers.sh do not change.
#
# Pins live in container/tools.json (the single source of truth for every
# version the image installs), read here with jq rather than restated, so a
# version bump is a manifest edit. The published package is verified against
# the pinned SHA-256 before it is extracted; nothing is piped into a shell and
# no floating "latest" is resolved.
#
# Two facts about this CLI shape the fragment:
#
#   * It is distributed as a **pure-JavaScript bundle** with no dependencies —
#     one artefact for every architecture, hence a single `noarch` checksum
#     (the per-architecture lookup below still works, so a future native
#     release needs no change here).
#   * That bundle runs on **Node.js**, which the image installs before the
#     provider layer. The check below fails loudly if it is ever reordered
#     away, rather than installing an agent that cannot start.
#
# Fails loud (Issue #3234): an unknown architecture, a missing pin, an
# unpinned checksum, an absent Node runtime, a failed download, a checksum
# mismatch, a bundle without its entry point, or a command that will not run
# aborts the build rather than producing an image whose agent is broken.
#
# Australian English spelling throughout (behaviour, organisation).

set -euo pipefail

PROVIDER_ID="gemini"
MANIFEST="${AGENT_PROVIDER_MANIFEST:-/tmp/tools.json}"
REGISTRY="https://registry.npmjs.org/@google/gemini-cli/-"
# Where the bundle is unpacked; /usr/local/bin holds only the launcher.
INSTALL_DIR="/usr/local/lib/gemini-cli"
# The bundle's entry point, as the package's own `bin` field names it.
ENTRY_POINT="gemini.js"

if [[ ! -f "${MANIFEST}" ]]; then
    echo "[${PROVIDER_ID}] Manifest ${MANIFEST} is missing — cannot resolve the pinned version" >&2
    exit 1
fi

# Read the pinned version and checksum. `jq -e` fails when the selection is
# absent or null, so an unpinned provider stops the build.
version="$(jq -er --arg id "${PROVIDER_ID}" \
    '.providers[] | select(.id == $id) | .version' "${MANIFEST}")"

arch="$(uname -m)"
case "${arch}" in
    x86_64) manifest_arch="amd64" ;;
    aarch64) manifest_arch="arm64" ;;
    *)
        echo "[${PROVIDER_ID}] Unsupported build architecture: ${arch}" >&2
        exit 1
        ;;
esac

# One artefact serves every architecture, so `noarch` is the pin; the
# per-architecture key is honoured first for a future native release.
checksum="$(jq -er --arg id "${PROVIDER_ID}" --arg arch "${manifest_arch}" \
    '.providers[] | select(.id == $id) | .sha256[$arch] // .sha256.noarch' \
    "${MANIFEST}")"

binary="$(jq -er --arg id "${PROVIDER_ID}" \
    '.providers[] | select(.id == $id) | .binary' "${MANIFEST}")"

if ! command -v node > /dev/null 2>&1; then
    echo "[${PROVIDER_ID}] node is not installed: this CLI is a JavaScript bundle, so the Node runtime layer must be built before the coding-agent provider layer" >&2
    exit 1
fi

echo "[${PROVIDER_ID}] Installing ${binary} ${version} for ${manifest_arch}"

workdir="$(mktemp -d)"
trap 'rm -rf "${workdir}"' EXIT

archive="${workdir}/gemini-cli.tgz"
curl -fsSL -o "${archive}" "${REGISTRY}/gemini-cli-${version}.tgz"
echo "${checksum}  ${archive}" | sha256sum -c -

# The published package holds the whole bundle under package/bundle.
tar -xzf "${archive}" -C "${workdir}" package/bundle
extracted="${workdir}/package/bundle"
if [[ ! -f "${extracted}/${ENTRY_POINT}" ]]; then
    echo "[${PROVIDER_ID}] Package does not contain bundle/${ENTRY_POINT}" >&2
    exit 1
fi

rm -rf "${INSTALL_DIR}"
mkdir -p "${INSTALL_DIR}"
cp -R "${extracted}/." "${INSTALL_DIR}/"
chmod -R a+rX "${INSTALL_DIR}"

# The launcher on PATH: the bundle is JavaScript, so the command every caller
# spawns is a small wrapper around the Node runtime.
cat > "/usr/local/bin/${binary}" <<EOF
#!/bin/sh
# Generated by container/providers/gemini.sh — do not edit.
exec node "${INSTALL_DIR}/${ENTRY_POINT}" "\$@"
EOF
chmod 0755 "/usr/local/bin/${binary}"

# Prove the installed command runs in this image rather than assuming it does.
installed="$("/usr/local/bin/${binary}" --version < /dev/null)"
case "${installed}" in
    *"${version}"*) ;;
    *)
        echo "[${PROVIDER_ID}] Installed command reports \"${installed}\", expected ${version}" >&2
        exit 1
        ;;
esac

echo "[${PROVIDER_ID}] Installed ${binary} ${installed}"
