/**
 * Apply the `degraded-model` label on a degraded planning run (Issue #2650).
 *
 * When a planning run's degradation verdict (#2649) is positive, the worker
 * makes silent model degradation visible at a glance (#2646) by labelling the
 * parent issue being planned and every sub-issue the run created with the
 * non-reserved `degraded-model` label.
 *
 * `best-model` is a reserved workflow label stripped by `label_security.ts`
 * when self-applied, so it cannot carry this signal — `degraded-model` is the
 * new non-reserved label the worker creates if missing.
 *
 * Every label operation here is **non-fatal**: a create or apply failure is
 * logged and never aborts the planning-run closure. Healthy runs apply nothing,
 * and the worker never removes the label (humans clear it after investigating).
 *
 * Uses Australian English throughout (behaviour, colour, organisation, etc.).
 */

import type { Logger } from "../types.ts";
import { getLabelByName } from "../setup/label_definitions.ts";
import { addLabelToIssue, ensureLabelExists } from "./label_operations.ts";

/** The canonical name of the degraded-model label (Issue #2650). */
export const DEGRADED_MODEL_LABEL = "degraded-model";

/**
 * Apply the `degraded-model` label to the parent issue and every sub-issue of
 * a degraded planning run.
 *
 * Ensures the label exists once (create-if-missing, mirroring the
 * `security`/`idle-task` pattern), then adds it to the parent issue and each
 * detected sub-issue number. All operations are non-fatal — failures are logged
 * via `logger.warn` and never thrown.
 *
 * @param args.repo - Repository in "owner/repo" format
 * @param args.parentIssueNumber - The planning (parent) issue number
 * @param args.subIssueNumbers - Issue numbers of the sub-issues created by the run
 * @param args.ghCommandFn - gh command runner (injected for testability)
 * @param args.logger - Logger for non-fatal warnings
 * @param args.cacheDir - Optional label-cache directory (injected for testability)
 */
export async function applyDegradedModelLabel(args: {
  repo: string;
  parentIssueNumber: number;
  subIssueNumbers: number[];
  ghCommandFn: (args: string[]) => Promise<string>;
  logger: Logger;
  cacheDir?: string;
}): Promise<void> {
  const { repo, parentIssueNumber, subIssueNumbers, ghCommandFn, logger } =
    args;
  const labelDeps = args.cacheDir
    ? { ghCommandFn, cacheDir: args.cacheDir }
    : { ghCommandFn };

  const def = getLabelByName(DEGRADED_MODEL_LABEL);
  const colour = def?.colour ?? "e99695";
  const description = def?.description ??
    "Generated by a model other than the configured planning model";

  // Create the label if missing (non-fatal). A failure here still lets the
  // add-label calls attempt — the label may already exist on the repo.
  try {
    const ensured = await ensureLabelExists(
      repo,
      DEGRADED_MODEL_LABEL,
      colour,
      description,
      labelDeps,
    );
    if (!ensured.ok) {
      logger.warn(
        "Failed to ensure degraded-model label exists (non-fatal)",
        { repo, error: ensured.error.message },
      );
    }
  } catch (err) {
    logger.warn("Failed to ensure degraded-model label exists (non-fatal)", {
      repo,
      error: err instanceof Error ? err.message : String(err),
    });
  }

  // De-duplicate so a sub-issue that is also the parent is labelled once.
  const targets = [...new Set([parentIssueNumber, ...subIssueNumbers])];

  for (const issueNumber of targets) {
    try {
      const added = await addLabelToIssue(
        repo,
        issueNumber,
        DEGRADED_MODEL_LABEL,
        labelDeps,
      );
      if (!added.ok) {
        logger.warn(
          "Failed to apply degraded-model label (non-fatal)",
          { repo, issueNumber, error: added.error.message },
        );
      }
    } catch (err) {
      logger.warn("Failed to apply degraded-model label (non-fatal)", {
        repo,
        issueNumber,
        error: err instanceof Error ? err.message : String(err),
      });
    }
  }
}
