/**
 * Auto-milestone for planning sub-issues (Issue #2863).
 *
 * When a planning run breaks an issue into two or more sub-issues and the
 * parent issue has no milestone of its own, the worker auto-creates a GitHub
 * milestone named `#<N> <short description>` (from the parent issue) and
 * assigns every sub-issue it created to that milestone. Assigning the
 * milestone is enough to opt the sub-issues into the existing milestone-branch
 * delivery workflow (Issue #1300): their PRs auto-merge into a shared
 * `milestone/<name>` branch and the default branch is only updated via the
 * single final milestone PR.
 *
 * Gating rules (always on, no opt-out):
 *   - Parent already has a milestone → no-op (the #1300 inheritance path keeps
 *     ownership; we never create a competing milestone).
 *   - Fewer than two sub-issues → no-op (a single sub-issue is handled directly,
 *     so it gets no milestone).
 *
 * One milestone per file-area group (Issue #2175): when the caller passes the
 * `## Milestones` groups the structural gate accepted (Issue #2172), the run
 * gets **one milestone per group** of two or more sub-issues — titled
 * `#<N> <area>: <short description>` — instead of one milestone for the whole
 * plan. A group of a single sub-issue gets no milestone and merges straight to
 * the default branch. Groups are independent: each has its own marker, so
 * neither a sibling group nor a later ungrouped run can adopt another group's
 * milestone. Without groups the behaviour is exactly as it was. The
 * four-milestone cap belongs to the gate, not here.
 *
 * Naming (Issue #1690): the title is `#<N> <short description>`, generated by
 * the one shared helper {@link buildPlanningMilestoneTitle} and bounded by
 * {@link MAX_MILESTONE_TITLE_LENGTH}. The `#<N>` prefix is the stable part —
 * two parents with near-identical titles cannot collide — and the description
 * is sanitised free of quotes, newlines and control characters so the title
 * stays workable in a terminal and in `gh` search expressions. Long issue
 * titles are never copied verbatim; milestone #50 was created that way and
 * ran to `#1653 The CLI now says "hit your session limit", which …`.
 *
 * Idempotent, and compatible with milestones created before that convention:
 * an existing milestone is matched by the structured `planning-milestone`
 * marker in its description, then by exact title, then by a leading `#<N>` —
 * so a legacy long title is reused **as it stands** and never renamed. The
 * whole flow is best-effort — callers treat a failure as non-fatal so planning
 * closure is never blocked.
 *
 * Australian English spelling used throughout.
 */

import { runGhCommand } from "./github.ts";
import type { MilestoneGroup } from "./plan_milestone_groups.ts";
import { trackingIssueFromMilestoneTitle } from "./milestone_sync_streak.ts";
import type { Logger } from "../types.ts";

// ---------------------------------------------------------------------------
// Title helper — the one place a planning milestone is named (Issue #1690)
// ---------------------------------------------------------------------------

/**
 * Maximum length of a generated milestone title, in characters, including the
 * `#<N> ` prefix.
 *
 * 60 keeps the title readable in the GitHub milestone list and short enough to
 * type and search from a terminal, while still leaving enough words after the
 * `#<N> ` prefix to say what the milestone is about. (The
 * `milestone/<name>` branch slug `createMilestoneBranchName` derives is capped
 * at 50 characters of its own, so the tail of a full-length title does not
 * reach the branch name.) Milestone #50 was created from a raw issue title and
 * ran to `#1653 The CLI now says "hit your session limit", which …` — long,
 * quoted, and awkward everywhere.
 */
export const MAX_MILESTONE_TITLE_LENGTH = 60;

/**
 * Quote characters, dropped outright rather than replaced by a space, so
 * `says "hit your session limit", which` reads as
 * `says hit your session limit, which` instead of gaining stray gaps.
 */
const QUOTE_CHARS = /['"`‘’“”«»]/gu;

/**
 * Allowlist of characters a milestone title may keep: letters, digits, spaces
 * and `- _ . , :` — punctuation that needs no quoting in a shell, a `gh`
 * search expression or a branch slug. Everything else becomes a space:
 * control characters and newlines, but also the shell metacharacters
 * (`& | ; $ ( ) < >`) and glob characters that make a title awkward to type
 * or search for. An allowlist, not a denylist, so a character nobody
 * anticipated is safe by default.
 */
const UNSAFE_CHARS = /[^\p{L}\p{N} \-_.,:]/gu;

/** Trailing punctuation left dangling by a truncation, stripped from the end. */
const TRAILING_PUNCTUATION = /[\s.,:_-]+$/u;

/**
 * Reduce free text to the safe character set: quotes removed, every other
 * disallowed character replaced by a space, whitespace runs collapsed, ends
 * trimmed.
 */
function sanitiseMilestoneTitleText(text: string): string {
  return text
    .replace(QUOTE_CHARS, "")
    .replace(UNSAFE_CHARS, " ")
    .replace(/\s+/gu, " ")
    .trim();
}

/**
 * Cut `text` to at most `limit` UTF-16 units without splitting a character.
 * Iterating code points rather than slicing means an astral-plane character
 * (an emoji, a CJK extension ideograph) is either kept whole or dropped — a
 * half-character lone surrogate is not a string GitHub will accept.
 */
function cutToLength(text: string, limit: number): string {
  if (text.length <= limit) return text;
  let kept = "";
  for (const character of text) {
    if (kept.length + character.length > limit) break;
    kept += character;
  }
  return kept;
}

/**
 * Cut `text` to at most `limit` characters on a word boundary, so the title
 * ends on a whole word rather than mid-word. A boundary is only honoured when
 * it keeps at least half the budget — otherwise one very long first word would
 * collapse the title to nothing and a hard cut is used instead.
 */
function boundToWords(text: string, limit: number): string {
  if (limit <= 0) return "";
  if (text.length <= limit) return text;
  const cut = cutToLength(text, limit);
  const lastSpace = cut.lastIndexOf(" ");
  const kept = lastSpace >= Math.floor(limit / 2)
    ? cut.slice(0, lastSpace)
    : cut;
  return kept.replace(TRAILING_PUNCTUATION, "");
}

/**
 * Build the canonical planning milestone title: `#<N> <short description>`,
 * bounded by {@link MAX_MILESTONE_TITLE_LENGTH} and free of quotes, newlines
 * and control characters (Issue #1690).
 *
 * The `#<N>` prefix is the stable, unambiguous part: two parent issues with
 * near-identical titles can never collide, and the number identifies the
 * milestone even when the descriptive tail is truncated. `plannedShortTitle`
 * wins when a caller has an explicit short name for the plan; otherwise the
 * parent issue title is sanitised and bounded. A description that sanitises
 * away entirely leaves the bare `#<N>`.
 *
 * @throws Error when `parentIssueNumber` is not a positive integer — a
 *   milestone with no usable identity must fail loudly, never be named after
 *   a bad number.
 */
export function buildPlanningMilestoneTitle(
  parentIssueNumber: number,
  parentIssueTitle: string,
  plannedShortTitle?: string,
  fileArea?: string,
): string {
  if (
    !Number.isSafeInteger(parentIssueNumber) || parentIssueNumber <= 0
  ) {
    throw new Error(
      `buildPlanningMilestoneTitle: invalid parent issue number ` +
        `"${parentIssueNumber}" — must be a positive integer`,
    );
  }
  const prefix = `#${parentIssueNumber}`;
  // The head is `#<N>`, or `#<N> <area>:` when the milestone belongs to a
  // file-area group. The area is bounded to half of what the prefix leaves, so
  // a verbose area can never squeeze the description out entirely.
  const area = boundToWords(
    sanitiseMilestoneTitleText(fileArea ?? ""),
    Math.floor((MAX_MILESTONE_TITLE_LENGTH - prefix.length - 1) / 2),
  ).replace(TRAILING_PUNCTUATION, "");
  const head = area === "" ? prefix : `${prefix} ${area}:`;

  const explicit = sanitiseMilestoneTitleText(plannedShortTitle ?? "");
  const source = explicit !== ""
    ? explicit
    : sanitiseMilestoneTitleText(parentIssueTitle);
  const description = boundToWords(
    source,
    MAX_MILESTONE_TITLE_LENGTH - head.length - 1,
  );
  return description === ""
    ? head.replace(TRAILING_PUNCTUATION, "")
    : `${head} ${description}`;
}

/**
 * Structured marker embedded in the description of every planning milestone
 * the worker creates, recording the parent issue in machine-readable form.
 *
 * Lookup matches this before it looks at any title, so reuse never depends on
 * parsing human-readable text: a milestone renamed in the UI is still found,
 * and a title that had to be truncated loses nothing that identity needs.
 */
export function planningMilestoneMarker(
  parentIssueNumber: number,
  fileArea?: string,
): string {
  const area = sanitiseMilestoneTitleText(fileArea ?? "");
  const areaAttribute = area === "" ? "" : ` area="${area}"`;
  return `<!-- planning-milestone parent="${parentIssueNumber}"${areaAttribute} -->`;
}

/**
 * Whether a milestone description carries a **grouped** planning marker — one
 * with an `area=` attribute.
 *
 * The ungrouped lookup's last resort is a bare leading `#<N>`, which every
 * group's milestone for the same parent also carries. Skipping descriptions
 * that name an area is what stops the ungrouped path from adopting one of the
 * plan's group milestones (Issue #2175).
 */
function carriesGroupedMarker(description: string): boolean {
  return /<!--\s*planning-milestone\s+parent="\d+"\s+area="/u.test(
    description,
  );
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface MaybeCreatePlanningMilestoneOptions {
  /** Target repository in `owner/repo` form. */
  repo: string;
  /** Parent planning issue number — the milestone title's stable prefix. */
  parentIssueNumber: number;
  /** Parent planning issue title — bounded into the milestone title. */
  parentIssueTitle: string;
  /**
   * Explicit short name for the plan, preferred over the parent issue title
   * when the caller has one (Issue #1690). Sanitised and bounded like any
   * other title text; blank falls back to the issue title.
   */
  plannedShortTitle?: string;
  /**
   * Existing milestone title on the parent issue, if any (Issue #1300
   * inheritance). When set, this helper is a no-op.
   */
  parentMilestoneTitle?: string;
  /** Sub-issue numbers created by this planning run. */
  subIssueNumbers: number[];
  /**
   * File-area groups from the parent's `## Milestones` table, when the
   * structural gate found and accepted one (Issue #2172). Given a non-empty
   * list, the helper creates **one milestone per group** of two or more
   * sub-issues instead of one milestone for the whole plan (Issue #2175).
   * Omitted — or empty — keeps the single-milestone behaviour exactly as it
   * was. The 4-milestone cap is the gate's rule, not this helper's.
   */
  groups?: readonly MilestoneGroup[];
  /** Injectable gh runner — defaults to the production retry wrapper. */
  ghCommandFn?: (args: string[]) => Promise<string>;
  /** Logger for non-fatal warnings. */
  logger: Logger;
}

export interface PlanningMilestoneOutcome {
  /** True when a milestone was ensured and sub-issues were assigned. */
  created: boolean;
  /**
   * The title of the milestone actually used, when `created` is true. This is
   * the generated title for a new milestone, and the **existing** title when
   * one was reused — a milestone is never renamed to match (Issue #1690).
   */
  milestoneTitle?: string;
  /** The milestone number GitHub reports — the structured identity. */
  milestoneNumber?: number;
  /** Sub-issue numbers successfully assigned to the milestone. */
  assigned: number[];
  /** Reason the helper was a no-op, when `created` is false. */
  skippedReason?: "parent-has-milestone" | "too-few-sub-issues";
  /**
   * One entry per group, in the order the groups were given — present only on
   * the grouped path (Issue #2175). On that path `milestoneTitle` and
   * `milestoneNumber` above are left unset because there is no single
   * milestone to name, and `assigned` is the union across the groups.
   */
  milestones?: PlanningMilestoneGroupOutcome[];
}

/** What one file-area group produced on the grouped path (Issue #2175). */
export interface PlanningMilestoneGroupOutcome {
  /** The group's file area, as the `## Milestones` table gave it. */
  area: string;
  /** The title of the milestone used, when one was ensured. */
  milestoneTitle?: string;
  /** The milestone number GitHub reports, when one was ensured. */
  milestoneNumber?: number;
  /** Sub-issue numbers successfully assigned to this group's milestone. */
  assigned: number[];
  /**
   * Why this group produced no milestone: a group of one sub-issue merges
   * straight to the default branch, and a GitHub failure is best-effort.
   */
  skippedReason?: "too-few-sub-issues" | "ensure-failed" | "naming-failed";
}

/** A milestone resolved from the API — number and title as GitHub holds them. */
interface ResolvedMilestone {
  number: number;
  title: string;
}

// ---------------------------------------------------------------------------
// maybeCreatePlanningMilestone
// ---------------------------------------------------------------------------

/**
 * Auto-create a milestone for a planning run's sub-issues and assign them all
 * to it, when the gating rules are met. See the module docstring for the rules.
 *
 * Best-effort: an ensure or assign failure is logged and swallowed so the
 * caller's planning closure is never blocked. A per-sub-issue assign failure
 * does not abort the remaining assignments.
 */
export async function maybeCreatePlanningMilestone(
  opts: MaybeCreatePlanningMilestoneOptions,
): Promise<PlanningMilestoneOutcome> {
  const {
    repo,
    parentIssueNumber,
    parentIssueTitle,
    plannedShortTitle,
    parentMilestoneTitle,
    subIssueNumbers,
    groups,
    logger,
  } = opts;
  const gh = opts.ghCommandFn ?? runGhCommand;

  // Gate 1: the parent already owns a milestone — keep the #1300 inheritance
  // path and never create a competing milestone. Grouping does not change
  // this: a plan whose parent owns a milestone still has one owner.
  if (parentMilestoneTitle && parentMilestoneTitle.trim() !== "") {
    return {
      created: false,
      assigned: [],
      skippedReason: "parent-has-milestone",
    };
  }

  // Gate 2: a milestone only makes sense for 2+ sub-issues.
  const unique = [...new Set(subIssueNumbers)].sort((a, b) => a - b);
  if (unique.length < 2) {
    return {
      created: false,
      assigned: [],
      skippedReason: "too-few-sub-issues",
    };
  }

  // Grouped path (Issue #2175): one milestone per file-area group carrying two
  // or more sub-issues. An empty list is not a grouping — it falls through to
  // the single-milestone path below, unchanged.
  if (groups !== undefined && groups.length > 0) {
    // A sub-issue the table never named would silently keep the default branch
    // while its siblings move to a milestone branch. The gate rejects that
    // (every published sub-issue must sit in exactly one row), so reaching
    // here means the sets disagree — report it rather than lose it quietly.
    const grouped = new Set(groups.flatMap((g) => g.subIssueNumbers));
    const ungrouped = unique.filter((n) => !grouped.has(n));
    if (ungrouped.length > 0) {
      logger.warn(
        "Planning milestone groups name no group for some sub-issues — they keep the default branch (Issue #2175)",
        {
          repo,
          parentIssueNumber,
          subIssueNumbers: ungrouped.join(", "),
        },
      );
    }
    return await createGroupedPlanningMilestones({
      repo,
      parentIssueNumber,
      parentIssueTitle,
      plannedShortTitle,
      groups,
      gh,
      logger,
    });
  }

  const outcome = await ensureAndAssignGroup({
    repo,
    parentIssueNumber,
    parentIssueTitle,
    plannedShortTitle,
    subIssueNumbers: unique,
    gh,
    logger,
  });
  if (outcome.milestone === null) return { created: false, assigned: [] };

  logger.info("Auto-created planning milestone for sub-issues (Issue #2863)", {
    repo,
    parentIssueNumber,
    milestoneTitle: outcome.milestone.title,
    milestoneNumber: outcome.milestone.number,
    assignedCount: outcome.assigned.length,
  });

  return {
    created: true,
    milestoneTitle: outcome.milestone.title,
    milestoneNumber: outcome.milestone.number,
    assigned: outcome.assigned,
  };
}

/**
 * Create one milestone per file-area group and assign each group's sub-issues
 * to its own milestone (Issue #2175).
 *
 * A group of a single sub-issue gets **no** milestone — it merges straight to
 * the default branch — and is still reported, so the caller can see that the
 * skip was deliberate rather than a failure. Groups are independent: a naming,
 * ensure or assign failure in one is logged and confined to that group, and
 * every remaining group still runs. The 4-milestone cap belongs to the
 * structural gate (Issue #2172) and is deliberately not re-implemented here.
 */
async function createGroupedPlanningMilestones(opts: {
  repo: string;
  parentIssueNumber: number;
  parentIssueTitle: string;
  plannedShortTitle?: string;
  groups: readonly MilestoneGroup[];
  gh: (args: string[]) => Promise<string>;
  logger: Logger;
}): Promise<PlanningMilestoneOutcome> {
  const { repo, parentIssueNumber, groups, logger } = opts;
  const milestones: PlanningMilestoneGroupOutcome[] = [];

  for (const group of groups) {
    const subIssueNumbers = [...new Set(group.subIssueNumbers)]
      .sort((a, b) => a - b);

    // A group of one merges straight to the default branch: no milestone, and
    // the skip is recorded rather than silent.
    if (subIssueNumbers.length < 2) {
      milestones.push({
        area: group.area,
        assigned: [],
        skippedReason: "too-few-sub-issues",
      });
      continue;
    }

    const outcome = await ensureAndAssignGroup({
      repo,
      parentIssueNumber,
      parentIssueTitle: opts.parentIssueTitle,
      // The table's milestone cell is the group's own short name; the plan's
      // short title (then the parent title) is the fallback when the row
      // carries none.
      plannedShortTitle: group.title.trim() !== ""
        ? group.title
        : opts.plannedShortTitle,
      fileArea: group.area,
      subIssueNumbers,
      gh: opts.gh,
      logger,
    });

    if (outcome.milestone === null) {
      milestones.push({
        area: group.area,
        assigned: [],
        skippedReason: outcome.failure ?? "ensure-failed",
      });
      continue;
    }
    milestones.push({
      area: group.area,
      milestoneTitle: outcome.milestone.title,
      milestoneNumber: outcome.milestone.number,
      assigned: outcome.assigned,
    });
  }

  const assigned = [
    ...new Set(milestones.flatMap((m) => m.assigned)),
  ].sort((a, b) => a - b);
  const created = milestones.some((m) => m.milestoneNumber !== undefined);

  logger.info(
    "Auto-created one planning milestone per file-area group (Issue #2175)",
    {
      repo,
      parentIssueNumber,
      groupCount: groups.length,
      milestoneCount: milestones.filter((m) => m.milestoneNumber !== undefined)
        .length,
      assignedCount: assigned.length,
    },
  );

  return { created, assigned, milestones };
}

/**
 * Name, ensure and populate one milestone — the single body both paths share.
 *
 * Best-effort by contract: a naming failure (an unusable parent issue number,
 * a caller bug) and an ensure failure (a GitHub hiccup) are logged apart and
 * reported as `milestone: null`, never thrown, so planning closure is never
 * aborted. A per-sub-issue assign failure does not abort the remaining
 * assignments.
 */
async function ensureAndAssignGroup(opts: {
  repo: string;
  parentIssueNumber: number;
  parentIssueTitle: string;
  plannedShortTitle?: string;
  fileArea?: string;
  subIssueNumbers: readonly number[];
  gh: (args: string[]) => Promise<string>;
  logger: Logger;
}): Promise<{
  milestone: ResolvedMilestone | null;
  assigned: number[];
  failure?: "ensure-failed" | "naming-failed";
}> {
  const { repo, parentIssueNumber, fileArea, gh, logger } = opts;

  let title: string;
  try {
    title = buildPlanningMilestoneTitle(
      parentIssueNumber,
      opts.parentIssueTitle,
      opts.plannedShortTitle,
      fileArea,
    );
  } catch (err) {
    logger.warn("Failed to name planning milestone (non-fatal)", {
      repo,
      parentIssueNumber,
      ...(fileArea === undefined ? {} : { fileArea }),
      error: err instanceof Error ? err.message : String(err),
    });
    return { milestone: null, assigned: [], failure: "naming-failed" };
  }

  let milestone: ResolvedMilestone;
  try {
    milestone = await ensurePlanningMilestone(
      repo,
      parentIssueNumber,
      title,
      gh,
      fileArea,
    );
  } catch (err) {
    logger.warn("Failed to ensure planning milestone (non-fatal)", {
      repo,
      parentIssueNumber,
      milestoneTitle: title,
      ...(fileArea === undefined ? {} : { fileArea }),
      error: err instanceof Error ? err.message : String(err),
    });
    return { milestone: null, assigned: [], failure: "ensure-failed" };
  }

  // Assign each sub-issue to the milestone that was actually resolved — a
  // reused legacy milestone keeps its own title, so assigning by the freshly
  // generated one would silently miss it. A single failure does not abort the
  // rest.
  const assigned: number[] = [];
  for (const n of opts.subIssueNumbers) {
    try {
      await gh([
        "issue",
        "edit",
        String(n),
        "--repo",
        repo,
        "--milestone",
        milestone.title,
      ]);
      assigned.push(n);
    } catch (err) {
      logger.warn(
        "Failed to assign sub-issue to planning milestone (non-fatal)",
        {
          repo,
          subIssueNumber: n,
          milestoneTitle: milestone.title,
          milestoneNumber: milestone.number,
          error: err instanceof Error ? err.message : String(err),
        },
      );
    }
  }

  return { milestone, assigned };
}

// ---------------------------------------------------------------------------
// Idempotent ensure
// ---------------------------------------------------------------------------

/**
 * Ensure an open milestone for `parentIssueNumber` exists in `repo`, returning
 * the milestone GitHub holds. An existing milestone is reused **as it stands**
 * — never renamed — so milestones created before Issue #1690 (milestone #50
 * and its long quoted title) keep working and no in-flight milestone branch is
 * disturbed. Repeated calls therefore make at most one POST per
 * `(repo, parent issue)` pair.
 */
async function ensurePlanningMilestone(
  repo: string,
  parentIssueNumber: number,
  title: string,
  gh: (args: string[]) => Promise<string>,
  fileArea?: string,
): Promise<ResolvedMilestone> {
  const endpoint = `repos/${repo}/milestones`;

  const listingRaw = await gh(["api", `${endpoint}?state=open&per_page=100`]);
  const existing = findPlanningMilestone(
    listingRaw,
    parentIssueNumber,
    title,
    fileArea,
  );
  if (existing !== null) return existing;

  const createRaw = await gh([
    "api",
    "-X",
    "POST",
    endpoint,
    "-f",
    `title=${title}`,
    "-f",
    `description=${buildDescription(parentIssueNumber, fileArea)}`,
  ]);
  const created = parseMilestone(createRaw, title);
  if (created === null) {
    throw new Error(
      `ensurePlanningMilestone: malformed create response for "${title}" in ${repo}`,
    );
  }
  return created;
}

/**
 * Description embedded in newly-created planning milestones. Leads with the
 * structured {@link planningMilestoneMarker} so later runs recover the parent
 * issue from machine-readable data rather than from the title text.
 */
function buildDescription(
  parentIssueNumber: number,
  fileArea?: string,
): string {
  const area = sanitiseMilestoneTitleText(fileArea ?? "");
  const scope = area === ""
    ? `the sub-issues of issue #${parentIssueNumber}`
    : `the \`${area}\` sub-issues of issue #${parentIssueNumber}`;
  return (
    `${planningMilestoneMarker(parentIssueNumber, fileArea)} ` +
    `Auto-created by planning (Issue #2863) — groups ${scope} ` +
    `for milestone-branch delivery.`
  );
}

/**
 * Find the open milestone that belongs to `parentIssueNumber` — and, on the
 * grouped path, to `fileArea` — in order of how much the evidence can be
 * trusted:
 *
 *   1. the structured `planning-milestone` marker in the description — the
 *      authoritative match, immune to renames and truncation. The marker
 *      carries the area, so a group only ever matches its own milestone;
 *   2. an exact match on the generated title;
 *   3. a leading `#<N>` on the title — the legacy shape, which is how
 *      milestones created before Issue #1690 (e.g. #50) are still found.
 *
 * Step 3 runs on the **ungrouped path only**, and skips any milestone whose
 * description carries an `area=` marker (Issue #2175). Every group milestone
 * of one plan leads with the same `#<N>`, so without both restrictions a group
 * — or an ungrouped re-run — would adopt a sibling group's milestone and pile
 * two streams of work onto one branch.
 *
 * Returns null when the listing is malformed or nothing matches, so a fresh
 * POST can recover.
 */
function findPlanningMilestone(
  raw: string,
  parentIssueNumber: number,
  wantTitle: string,
  fileArea?: string,
): ResolvedMilestone | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (!Array.isArray(parsed)) return null;

  const entries: { milestone: ResolvedMilestone; description: string }[] = [];
  for (const entry of parsed) {
    if (entry === null || typeof entry !== "object") continue;
    const r = entry as Record<string, unknown>;
    if (typeof r.number !== "number" || typeof r.title !== "string") continue;
    entries.push({
      milestone: { number: r.number, title: r.title },
      description: typeof r.description === "string" ? r.description : "",
    });
  }

  const marker = planningMilestoneMarker(parentIssueNumber, fileArea);
  const byMarker = entries.find((e) => e.description.includes(marker));
  if (byMarker) return byMarker.milestone;

  const byTitle = entries.find((e) => e.milestone.title === wantTitle);
  if (byTitle) return byTitle.milestone;

  // Grouped lookups stop here: a group's identity is its marker or its exact
  // title, never a prefix a sibling group shares.
  if (sanitiseMilestoneTitleText(fileArea ?? "") !== "") return null;

  const byPrefix = entries.find((e) =>
    !carriesGroupedMarker(e.description) &&
    trackingIssueFromMilestoneTitle(e.milestone.title) === parentIssueNumber
  );
  return byPrefix ? byPrefix.milestone : null;
}

/**
 * Parse the single-object response from the milestone create endpoint. The
 * number is the identity and must be present; a response that omits the title
 * falls back to the title just POSTed, which is what GitHub stored.
 */
function parseMilestone(
  raw: string,
  postedTitle: string,
): ResolvedMilestone | null {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return null;
  }
  if (parsed === null || typeof parsed !== "object") return null;
  const r = parsed as Record<string, unknown>;
  if (typeof r.number !== "number") return null;
  return {
    number: r.number,
    title: typeof r.title === "string" && r.title !== ""
      ? r.title
      : postedTitle,
  };
}
